### ISSUE TITLE
Build with boost-1.66.0 fails

### ISSUE THREAD

**Issue by AkioNak** [ElementsProject/elements#298]
### Describe the issue

Building Elements will fail to complie 'miner.cpp'.

#### If so, please list the steps to reproduce below:
1. brew update
2. make clean
3. make -j8

### Expected behaviour
Building Elements will successfully done.

### Actual behaviour
following error has occured.
```
In file included from miner.cpp:6:
In file included from ./miner.h:10:
In file included from ./txmempool.h:25:
In file included from /usr/local/include/boost/multi_index/ordered_index.hpp:17:
//usr/local/include/boost/multi_index/detail/ord_index_impl.hpp:1181:10: error: no matching function for call to object of type 'const key_compare'
      (aka 'const CompareModifiedEntry')
      if(comp_(key(v),key(y->value())))return false;
         ^~~~~

...

In file included from miner.cpp:6:
In file included from ./miner.h:10:
In file included from ./txmempool.h:25:
In file included from /usr/local/include/boost/multi_index/ordered_index.hpp:17:

/usr/local/include/boost/multi_index/detail/ord_index_impl.hpp:1186:26: error: no matching function for call to object of type 'const key_compare'
      (aka 'const CompareModifiedEntry')
    return y==header()||!comp_(key(y->value()),key(v));
                         ^~~~~

...

2 errors generated.
make[2]: *** [libbitcoin_server_a-miner.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
$ ls -l /usr/local/include/boost
lrwxr-xr-x  1 *****  admin  36 12 20 09:43 /usr/local/include/boost -> ../Cellar/boost/1.66.0/include/boost
$ uname -v
Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64

```

### What version of bitcoin-core are you using?
elements-0.14.1 (commit 9627f30bd7e351c93a141d3e4e2f8676ad5a7d6f)

### Machine specs:
- OS: macos 10.13.2
- CPU: Intel Core i7 2.2GHz
- RAM: 16GB
- Disk size: 256GB
- Disk Type (HD/SDD): SSD

### Any extra information that might be useful in the debugging process.
I think this is incompatibility problem with boost-1.66.0  and apply following PR may resolve this issue.

https://github.com/bitcoin/bitcoin/pull/11847

**Comment by instagibbs** [comment]
could you cherry-pick and check? I don't have OSX to test.

**Comment by AkioNak** [comment]
@instagibbs yes, of course.

**Comment by AkioNak** [comment]
@instagibbs Cherry-picking code (#299) is fine with ```make check``` and ```./qa/pull-tester/rpc-tests.py```  on the Mac.

[make_check.log](https://github.com/ElementsProject/elements/files/1585214/make_check.log)
[rpc_test.log](https://github.com/ElementsProject/elements/files/1585213/rpc_test.log)

**Comment by AkioNak** [comment]
#299

**Comment by chairmin** [comment]
You can follow it!
https://github.com/qtumproject/qtum/issues/447
